name: Midge Flinn
favicon: null
layout_spectrum: 0.8183711254969239
typography_spectrum: 0.22984637483023107
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2969609694555402
  lightness: 0.095076743979007
  saturation: 0.0541714399587363
  rhythmicContrast: 0.6878367534372956
purpose: []
